#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

# Import common cmd
source ./experimental_helper.sh
source ./_common.sh

# Retrieve arguments
ynh_script_progression --message="Loading installation settings..."
domain=$(ynh_app_setting_get --app $app --key domain)
path_url=$(ynh_normalize_url_path --path_url $(ynh_app_setting_get --app $app --key path))
is_public=$(ynh_app_setting_get --app $app --key is_public)
final_path=$(ynh_app_setting_get --app $app --key final_path)
default_home_server=$(ynh_app_setting_get --app $app --key default_home_server)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================

# Get source and install in source dir
ynh_script_progression --message="Upgrading source files..." --weight=6
ynh_secure_remove --file=$final_path
mkdir -p $final_path
cat > $final_path/index.html << EOF
<h1>Riot have been migrated to 'Element'.</h1>
<p>Please migrate your app to element as described at this following link:<br />
<a href="https://github.com/YunoHost-Apps/element_ynh/tree/testing#migration-from-old-app-name-riot">https://github.com/YunoHost-Apps/element_ynh/tree/testing#migration-from-old-app-name-riot</a></p>
EOF

ynh_script_progression --message="Configuring application..."

# Update Riot config
config_riot

# Remove the dedicated php-fpm config
ynh_remove_fpm_config

# Delete a system user
ynh_script_progression --message="Removing apps user..."
ynh_system_user_delete --username $app

# Update nginx config
ynh_add_nginx_config

#=================================================
# GENERIC FINALIZATION
#=================================================

# Set final permission
ynh_script_progression --message="Protecting directory..."
set_permission

# Recharge la configuration Nginx
systemctl reload nginx.service

ynh_script_progression --message="Upgrade of $app completed" --last
